=== nao-f-lll/nao-f-lll.github.io/clasificacion/clasificacion.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="clasificacion">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="fila" maxOccurs="8" minOccurs="6">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="xs:integer" name="posicion"></xs:element>
            <xs:element name="equipo">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:string" name="logo"></xs:element>
                  <xs:element type="xs:string" name="nombre"></xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element type="xs:integer" name="partidos"></xs:element>
            <xs:element type="xs:integer" name="victorias"></xs:element>
            <xs:element type="xs:integer" name="derrotas"></xs:element>
            <xs:element type="xs:integer" name="empates"></xs:element>
            <xs:element type="xs:integer" name="puntos"></xs:element>
          </xs:sequence>
          <xs:attribute type="xs:integer" name="id"/>
        </xs:complexType>  
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>


</xs:schema>

=== nao-f-lll/nao-f-lll.github.io/clasificacion/2023.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="clasificacion.xsl" type="text/xsl"?>
<clasificacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clasificacion.xsd">
<fila id="1">
 <posicion>1</posicion>
<equipo>
<logo>../media/Imagenes/logos/all_blacks_badge_white.png</logo>
<nombre>AllBlacks</nombre>
</equipo>
<partidos>10</partidos>
<victorias>8</victorias>
<derrotas>2</derrotas>
<empates>0</empates>
<puntos>435</puntos>
</fila>
<fila id="2">
 <posicion>2</posicion>
<equipo>
<logo>../media/Imagenes/logos/south_Africa_national_rugby_union_team.png</logo>
<nombre>Springboks</nombre>
</equipo>
<partidos>10</partidos>
<victorias>6</victorias>
<derrotas>4</derrotas>
<empates>0</empates>
<puntos>546</puntos>
</fila>
<fila id="3">
 <posicion>3</posicion>
<equipo>
<logo>../media/Imagenes/logos/sakuras-logo.png</logo>
<nombre>Sakuras</nombre>
</equipo>
<partidos>10</partidos>
<victorias>5</victorias>
<derrotas>4</derrotas>
<empates>1</empates>
<puntos>665</puntos>
</fila>
<fila id="4">
 <posicion>4</posicion>
<equipo>
<logo>../media/Imagenes/logos/shamrock-logo.png</logo>
<nombre>Shamrock</nombre>
</equipo>
<partidos>10</partidos>
<victorias>5</victorias>
<derrotas>5</derrotas>
<empates>0</empates>
<puntos>431</puntos>
</fila>
<fila id="5">
 <posicion>5</posicion>
<equipo>
<logo>../media/Imagenes/logos/red_rose_logo.png</logo>
<nombre>RedRose</nombre>
</equipo>
<partidos>10</partidos>
<victorias>3</victorias>
<derrotas>7</derrotas>
<empates>0</empates>
<puntos>402</puntos>
</fila>
<fila id="6">
 <posicion>6</posicion>
<equipo>
<logo>../media/Imagenes/logos/wallabies-logo.png</logo>
<nombre>Wallabies</nombre>
</equipo>
<partidos>10</partidos>
<victorias>2</victorias>
<derrotas>7</derrotas>
<empates>1</empates>
<puntos>500</puntos>
</fila>
</clasificacion>

=== nao-f-lll/nao-f-lll.github.io/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xml/clasificacion.xsl" type="text/xsl"?>
<clasificacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xml/clasificacion.xsd">

<fila id="1">
 <posicion>1</posicion>
<equipo>
<logo>media/Imagenes/logos/thistle_logo.png</logo>
<nombre>Thistle</nombre>
</equipo>
<partidos>10</partidos>
<victorias>6</victorias>
<derrotas>3</derrotas>
<empates>1</empates>
<puntos>598</puntos>
</fila>
<fila id="2">
 <posicion>2</posicion>
<equipo>
<logo>media/Imagenes/logos/all_blacks_badge_white.png</logo>
<nombre>AllBlacks</nombre>
</equipo>
<partidos>10</partidos>
<victorias>5</victorias>
<derrotas>5</derrotas>
<empates>0</empates>
<puntos>581</puntos>
</fila>
<fila id="3">
 <posicion>3</posicion>
<equipo>
<logo>media/Imagenes/logos/feathers_logo.png</logo>
<nombre>Feathers</nombre>
</equipo>
<partidos>10</partidos>
<victorias>5</victorias>
<derrotas>5</derrotas>
<empates>0</empates>
<puntos>509</puntos>
</fila>
<fila id="4">
 <posicion>4</posicion>
<equipo>
<logo>media/Imagenes/logos/red_rose_logo.png</logo>
<nombre>RedRose</nombre>
</equipo>
<partidos>10</partidos>
<victorias>4</victorias>
<derrotas>5</derrotas>
<empates>1</empates>
<puntos>491</puntos>
</fila>
<fila id="5">
 <posicion>5</posicion>
<equipo>
<logo>media/Imagenes/logos/shamrock-logo.png</logo>
<nombre>Shamrock</nombre>
</equipo>
<partidos>10</partidos>
<victorias>4</victorias>
<derrotas>5</derrotas>
<empates>1</empates>
<puntos>470</puntos>
</fila>
<fila id="6">
 <posicion>6</posicion>
<equipo>
<logo>media/Imagenes/logos/south_Africa_national_rugby_union_team.png</logo>
<nombre>Springboks</nombre>
</equipo>
<partidos>10</partidos>
<victorias>4</victorias>
<derrotas>5</derrotas>
<empates>1</empates>
<puntos>382</puntos>
</fila>
</clasificacion>
